from datetime import datetime
import re

from email_validator import EmailNotValidError, validate_email
from pydantic import AliasChoices, BaseModel, ConfigDict, EmailStr, Field, field_validator, model_validator

from app.config import settings
from app.models import OrderStatus, PaymentMethod, PaymentStatus, Role


class ORMModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)


class AccountCreate(BaseModel):
    name: str = Field(min_length=2, max_length=120)
    email: EmailStr
    phone: str | None = Field(default=None, max_length=32)
    password: str = Field(min_length=10, max_length=128)


class AdminAccountCreate(BaseModel):
    """A staff account provisioned by an administrator.

    The initial password is deliberately generated by the server, never sent
    from nor retained by the browser.
    """

    name: str = Field(min_length=2, max_length=120)
    email: EmailStr
    phone: str = Field(min_length=3, max_length=32)
    role: Role

    @field_validator("name")
    @classmethod
    def required_name(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("A name is required")
        return value

    @field_validator("phone")
    @classmethod
    def required_phone(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("A mobile number is required")
        return value


class LoginRequest(BaseModel):
    email: str = Field(min_length=3, max_length=255)
    password: str

    @field_validator("email")
    @classmethod
    def valid_login_email(cls, value: str) -> str:
        email = value.strip().lower()
        # The local seed account uses a .local address, which is intentionally
        # accepted for development only. Public registration still requires a
        # standard email address, and production login rejects special-use TLDs.
        if settings.environment.casefold() != "production" and re.fullmatch(r"[^@\s]+@[a-z0-9-]+\.local", email):
            return email
        try:
            return validate_email(email, check_deliverability=False).normalized
        except EmailNotValidError as exc:
            raise ValueError("Enter a valid email address") from exc


class GoogleLoginRequest(BaseModel):
    credential: str = Field(min_length=10, max_length=4096)


class PasswordResetRequest(BaseModel):
    email: str = Field(min_length=3, max_length=255)

    @field_validator("email")
    @classmethod
    def valid_email(cls, value: str) -> str:
        email = value.strip().lower()
        if settings.environment.casefold() != "production" and re.fullmatch(r"[^@\s]+@[a-z0-9-]+\.local", email):
            return email
        try:
            return validate_email(email, check_deliverability=False).normalized
        except EmailNotValidError as exc:
            raise ValueError("Enter a valid email address") from exc


class PasswordResetConfirm(BaseModel):
    email: str = Field(min_length=3, max_length=255)
    otp: str = Field(pattern=r"^\d{6}$")
    new_password: str = Field(min_length=10, max_length=128)

    @field_validator("email")
    @classmethod
    def normalize_email(cls, value: str) -> str:
        return PasswordResetRequest.valid_email(value)


class AccountOut(ORMModel):
    id: int
    name: str
    # Account emails were validated when accepted. Keep the output as text so
    # development-only .local seed addresses can be returned to the client.
    email: str
    phone: str | None
    addresses: list[dict] = Field(default_factory=list)
    role: Role
    must_change_password: bool
    is_accepting_deliveries: bool = False
    created_at: datetime

    @model_validator(mode="before")
    @classmethod
    def serialize_addresses(cls, value):
        if hasattr(value, "addresses"):
            data = dict(value.__dict__)
            data["addresses"] = [
                {**{key: getattr(address, key) for key in (
                    "address_id", "label", "house_number", "road", "area", "city",
                    "pincode", "landmark", "latitude", "longitude", "is_default",
                )}, "id": address.address_id}
                for address in (value.addresses or [])
            ]
            data["addresses"] = [{("id" if key == "address_id" else key): val for key, val in item.items()} for item in data["addresses"]]
            return data
        return value


class ProvisionedAccountOut(AccountOut):
    temporary_password: str | None = None
    notification_status: str


class SavedAddressInput(BaseModel):
    id: str = Field(min_length=1, max_length=64)
    label: str = Field(min_length=1, max_length=40)
    house_number: str = Field(default="", max_length=120)
    area: str = Field(default="", max_length=160)
    road: str = Field(default="", max_length=160)
    landmark: str = Field(default="", max_length=200)
    city: str = Field(default="", max_length=120)
    pincode: str = Field(default="", max_length=20, validation_alias=AliasChoices("pincode", "postal_code"))
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)
    is_default: bool = False

    @field_validator("house_number", "road", "area", "city", "pincode", "landmark")
    @classmethod
    def trim_address_parts(cls, value: str) -> str:
        return value.strip()

    @model_validator(mode="after")
    def pinned_address_is_complete(self):
        has_latitude = self.latitude is not None
        has_longitude = self.longitude is not None
        if has_latitude != has_longitude:
            raise ValueError("Save both map coordinates together")
        if has_latitude and any(not getattr(self, field) for field in ("house_number", "road", "area", "city", "pincode")):
            raise ValueError("Complete the house or flat, road, area, city, and PIN code for a pinned address")
        return self


class AccountProfileUpdate(BaseModel):
    name: str = Field(min_length=2, max_length=120)
    email: EmailStr
    phone: str | None = Field(default=None, max_length=32)
    addresses: list[SavedAddressInput] | None = Field(default=None, max_length=12)


class PasswordUpdate(BaseModel):
    current_password: str
    new_password: str = Field(min_length=10, max_length=128)


class CartItemUpdate(BaseModel):
    quantity: int = Field(ge=0, le=99)


class CartItemOut(ORMModel):
    menu_item_id: int
    quantity: int


class AccountsPageOut(BaseModel):
    items: list[AccountOut]
    total: int
    limit: int
    offset: int
    role_counts: dict[str, int]


class TokenOut(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int
    account: AccountOut


class MenuItemVariationInput(BaseModel):
    name: str = Field(min_length=1, max_length=60)
    price_paise: int = Field(gt=0, le=10_000_000)


class MenuItemInput(BaseModel):
    name: str = Field(min_length=2, max_length=120)
    description: str = Field(default="", max_length=2000)
    category_id: int | None = None
    category: str | None = Field(default=None, max_length=80)
    price_paise: int = Field(gt=0, le=10_000_000)
    image_url: str | None = Field(default=None, max_length=500)
    image_urls: list[str] = Field(default_factory=list, max_length=20)
    is_vegetarian: bool = False
    is_available: bool = True
    is_featured: bool = False
    variations: list[MenuItemVariationInput] = Field(default_factory=list)


class MenuItemOut(ORMModel):
    id: int
    name: str
    description: str
    category_id: int | None
    category: str = ""
    price_paise: int
    discount_percent: int = 0
    discounted_price_paise: int | None = None
    image_urls: list[str]
    image_url: str | None = None
    is_vegetarian: bool
    is_available: bool
    is_featured: bool
    variations: list[dict] = Field(default_factory=list)
    discount_campaign_name: str | None = None
    popularity_count: int = 0

    @model_validator(mode="before")
    @classmethod
    def derive_menu_fields(cls, value):
        if hasattr(value, "image_urls"):
            import json
            data = dict(value.__dict__)
            data["image_url"] = (value.image_urls or [None])[0]
            cat = getattr(value, "category", None)
            data["category"] = cat.name if cat else ""
            vars_val = data.get("variations")
            if isinstance(vars_val, str):
                try:
                    data["variations"] = json.loads(vars_val)
                except Exception:
                    data["variations"] = []
            elif vars_val is None:
                data["variations"] = []

            # If variations exist, show lowest possible price
            vars_list = data.get("variations") or []
            if vars_list:
                min_price = min(v.get("price_paise", data["price_paise"]) for v in vars_list if isinstance(v, dict))
                data["price_paise"] = min_price

            return data
        return value


class MenuCategoryInput(BaseModel):
    name: str = Field(min_length=2, max_length=80)


class MenuCategoryOut(ORMModel):
    id: int
    name: str


class MenuCategoryDeleteOut(BaseModel):
    affected_menus: int


class OrderLineInput(BaseModel):
    menu_item_id: int | None = None
    custom_menu_item_id: int | None = None
    quantity: int = Field(gt=0, le=30)
    customizations: list[dict] = Field(default_factory=list)
    variation_name: str | None = None

    @model_validator(mode="after")
    def has_an_item(self):
        if self.menu_item_id is None and self.custom_menu_item_id is None:
            raise ValueError("Must provide either menu_item_id or custom_menu_item_id")
        return self


class OrderCreate(BaseModel):
    items: list[OrderLineInput] = Field(min_length=1, max_length=40)
    payment_method: PaymentMethod
    address: str = Field(default="", max_length=500)
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)
    notes: str = Field(default="", max_length=500)

    @model_validator(mode="after")
    def delivery_coordinates_are_paired(self):
        if (self.latitude is None) != (self.longitude is None):
            raise ValueError("Save both delivery coordinates together")
        return self
    scheduled_for: datetime | None = None

    @field_validator("items")
    @classmethod
    def unique_items(cls, items: list[OrderLineInput]) -> list[OrderLineInput]:
        import json
        keys = []
        for item in items:
            custom_key = json.dumps(item.customizations, sort_keys=True) if item.customizations else ""
            var_key = item.variation_name or ""
            keys.append((item.menu_item_id, item.custom_menu_item_id, var_key, custom_key))
        if len(keys) != len(set(keys)):
            raise ValueError("Each menu item selection can only appear once; adjust its quantity instead.")
        return items


class OrderStatusUpdate(BaseModel):
    status: OrderStatus


class OrderOut(BaseModel):
    order_id: str
    customer_id: int | None
    customer_name: str
    customer_email: str
    customer_phone: str | None
    status: OrderStatus
    order_type: str
    payment_method: PaymentMethod
    payment_status: PaymentStatus
    subtotal_paise: int
    tax_paise: int
    delivery_fee_paise: int
    total_paise: int
    address: str
    notes: str
    assigned_delivery_id: int | None
    created_at: datetime
    items: list[dict]


class AdminOrdersPageOut(BaseModel):
    items: list[OrderOut]
    total: int
    limit: int
    offset: int
    status_counts: dict[str, int]
    paid_revenue_paise: int


class RestaurantSettingsInput(BaseModel):
    restaurant_name: str = Field(min_length=2, max_length=120)
    tagline: str = Field(max_length=200)
    phone: str = Field(max_length=300)
    phones: list[str] = Field(default_factory=list)
    address: str = Field(max_length=300)
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)
    weekly_schedule: dict = Field(default_factory=dict)
    minimum_order_paise: int = Field(ge=0, le=10_000_000)
    delivery_radius_km: float = Field(ge=0.1, le=500)
    free_delivery_radius_km: float = Field(ge=0, le=500)
    delivery_fee_per_km_paise: int = Field(ge=0, le=1_000_000)
    accepting_orders: bool
    admin_override_open: bool | None = None
    distance_calculation_mode: str = Field(default="AUTO", pattern=r"^(AUTO|GOOGLE_MAPS|HAVERSINE)$")
    enforce_driver_geofence: bool = Field(default=False)
    driver_geofence_meters: int = Field(default=500, ge=50, le=50000)
    haversine_routing_factor: float = Field(default=1.3, ge=1.0, le=4.0)


class RestaurantSettingsOut(ORMModel):
    id: int
    restaurant_name: str
    tagline: str
    phone: str
    phones: list[str] = Field(default_factory=list)
    address: str
    latitude: float | None
    longitude: float | None
    weekly_schedule: dict
    minimum_order_paise: int
    delivery_radius_km: float
    free_delivery_radius_km: float
    delivery_fee_per_km_paise: int
    accepting_orders: bool
    admin_override_open: bool = False
    distance_calculation_mode: str = "AUTO"
    enforce_driver_geofence: bool = False
    driver_geofence_meters: int = 500
    haversine_routing_factor: float = 1.3

    @model_validator(mode="before")
    @classmethod
    def derive_phones(cls, value):
        data = dict(value.__dict__) if hasattr(value, "__dict__") else dict(value)
        raw_phone = data.get("phone") or ""
        phones = [p.strip() for p in raw_phone.split(",") if p.strip()]
        data["phones"] = phones
        return data


class DriverDutyInput(BaseModel):
    accepting: bool
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)


class DispatchInput(BaseModel):
    delivery_id: int


class BatchCreate(BaseModel):
    order_ids: list[str] = Field(min_length=1, max_length=12)
    route_label: str = Field(default="Nearby route", min_length=2, max_length=120)


class VerifyOtpInput(BaseModel):
    otp: str = Field(pattern=r"^\d{6}$")


class BatchClaimInput(BaseModel):
    order_ids: list[str] = Field(min_length=1, max_length=50)

    @field_validator("order_ids")
    @classmethod
    def unique_order_ids(cls, value: list[int]) -> list[int]:
        if len(value) != len(set(value)):
            raise ValueError("A delivery may only appear once in a batch")
        return value


class DraftInput(BaseModel):
    customer_name: str = Field(default="Walk-in", max_length=120)
    payload: dict = Field(default_factory=dict)


class MenuPauseInput(BaseModel):
    mode: str = Field(pattern=r"^(today|manual)$")


class OfferInput(BaseModel):
    audience: str = Field(pattern=r"^(ALL|NEW|RETURNING)$")
    channels: list[str] = Field(min_length=1)
    subject: str = Field(default="A little something from KebabZilla", min_length=2, max_length=160)
    message: str = Field(min_length=2, max_length=1000)

    @field_validator("channels")
    @classmethod
    def valid_channels(cls, value: list[str]) -> list[str]:
        if not value or any(channel not in {"SMS", "EMAIL"} for channel in value):
            raise ValueError("Choose SMS, email, or both")
        return list(dict.fromkeys(value))


class MenuDiscountInput(BaseModel):
    menu_item_ids: list[int] = Field(default_factory=list)
    custom_menu_item_ids: list[int] = Field(default_factory=list)
    campaign_name: str | None = Field(default=None, max_length=80)
    discount_percent: int = Field(ge=1, le=99)
    starts_at: datetime
    ends_at: datetime

    @model_validator(mode="after")
    def valid_range(self):
        if not self.menu_item_ids and not self.custom_menu_item_ids:
            raise ValueError("Select at least one menu item or custom menu item")
        if self.starts_at.tzinfo is None or self.ends_at.tzinfo is None:
            raise ValueError("Discount start and end times must include a timezone")
        if self.ends_at <= self.starts_at:
            raise ValueError("Discount end time must be after its start time")
        if self.campaign_name is not None:
            self.campaign_name = self.campaign_name.strip() or None
        return self


class CustomMenuSectionOptionInput(BaseModel):
    name: str = Field(min_length=1, max_length=120)
    extra_paise: int = Field(ge=0, le=10_000_000)


class CustomMenuSectionInput(BaseModel):
    name: str = Field(min_length=1, max_length=120)
    required: bool = True
    options: list[CustomMenuSectionOptionInput] = Field(min_length=1, max_length=20)


class CustomMenuItemInput(BaseModel):
    name: str = Field(min_length=2, max_length=120)
    description: str = Field(default="", max_length=2000)
    category_id: int | None = None
    category: str | None = None
    base_price_paise: int = Field(gt=0, le=10_000_000)
    image_urls: list[str] = Field(default_factory=list, max_length=20)
    is_vegetarian: bool = False
    is_available: bool = True
    is_featured: bool = False
    sections: list[CustomMenuSectionInput] = Field(default_factory=list, max_length=10)


class CustomMenuSectionOut(ORMModel):
    id: int
    name: str
    position: int
    required: bool = True
    options: list[dict]


class CustomMenuItemOut(ORMModel):
    id: int
    name: str
    description: str
    category_id: int | None
    category: str = ""
    base_price_paise: int
    lowest_price_paise: int = 0
    discount_percent: int = 0
    discounted_base_price_paise: int | None = None
    discount_campaign_name: str | None = None
    image_urls: list[str]
    image_url: str | None = None
    is_vegetarian: bool
    is_available: bool
    is_featured: bool
    sections: list[CustomMenuSectionOut]

    @model_validator(mode="before")
    @classmethod
    def derive_custom_fields(cls, value):
        if hasattr(value, "image_urls"):
            data = dict(value.__dict__)
            data["image_url"] = (value.image_urls or [None])[0]
            cat = getattr(value, "category", None)
            data["category"] = cat.name if cat else ""

            # Calculate lowest possible price
            # base price + minimum price from each mandatory/required section
            secs = getattr(value, "sections", []) or []
            lowest = data.get("base_price_paise", 0)
            for sec in secs:
                is_req = getattr(sec, "required", True) if hasattr(sec, "required") else sec.get("required", True)
                opts = getattr(sec, "options", []) if hasattr(sec, "options") else sec.get("options", [])
                if is_req and opts:
                    min_extra = min(
                        (opt.get("extra_paise", 0) if isinstance(opt, dict) else getattr(opt, "extra_paise", 0))
                        for opt in opts
                    )
                    lowest += min_extra
            data["lowest_price_paise"] = lowest
            return data
        return value

